/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAchievementsRouteImport } from './routes/_app/achievements'
import { Route as AppEndlessRouteImport } from './routes/_app/endless'
import { Route as AppLevelsIndexRouteImport } from './routes/_app/levels.index'
import { Route as AppLevelsLevelIdRouteImport } from './routes/_app/levels.$levelId'
import { Route as AppLibraryIndexRouteImport } from './routes/_app/library/index'
import { Route as AppPlayPoemIdRouteImport } from './routes/_app/play.$poemId'
import { Route as AppPracticeIndexRouteImport } from './routes/_app/practice.index'
import { Route as AppPracticePoemIdRouteImport } from './routes/_app/practice.$poemId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppLibraryCollectionIdIndexRouteImport } from './routes/_app/library/$collectionId/index'
import { Route as AppLibraryCollectionIdChapterIdIndexRouteImport } from './routes/_app/library/$collectionId/$chapterId/index'
import { Route as AppLibraryCollectionIdChapterIdAuthorIdRouteImport } from './routes/_app/library/$collectionId/$chapterId/$authorId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAchievementsRoute = AppAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => AppRoute,
} as any)
const AppEndlessRoute = AppEndlessRouteImport.update({
  id: '/endless',
  path: '/endless',
  getParentRoute: () => AppRoute,
} as any)
const AppLevelsIndexRoute = AppLevelsIndexRouteImport.update({
  id: '/levels/',
  path: '/levels/',
  getParentRoute: () => AppRoute,
} as any)
const AppLevelsLevelIdRoute = AppLevelsLevelIdRouteImport.update({
  id: '/levels/$levelId',
  path: '/levels/$levelId',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryIndexRoute = AppLibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => AppRoute,
} as any)
const AppPlayPoemIdRoute = AppPlayPoemIdRouteImport.update({
  id: '/play/$poemId',
  path: '/play/$poemId',
  getParentRoute: () => AppRoute,
} as any)
const AppPracticeIndexRoute = AppPracticeIndexRouteImport.update({
  id: '/practice/',
  path: '/practice/',
  getParentRoute: () => AppRoute,
} as any)
const AppPracticePoemIdRoute = AppPracticePoemIdRouteImport.update({
  id: '/practice/$poemId',
  path: '/practice/$poemId',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLibraryCollectionIdIndexRoute =
  AppLibraryCollectionIdIndexRouteImport.update({
    id: '/library/$collectionId/',
    path: '/library/$collectionId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppLibraryCollectionIdChapterIdIndexRoute =
  AppLibraryCollectionIdChapterIdIndexRouteImport.update({
    id: '/library/$collectionId/$chapterId/',
    path: '/library/$collectionId/$chapterId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppLibraryCollectionIdChapterIdAuthorIdRoute =
  AppLibraryCollectionIdChapterIdAuthorIdRouteImport.update({
    id: '/library/$collectionId/$chapterId/$authorId',
    path: '/library/$collectionId/$chapterId/$authorId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/achievements': typeof AppAchievementsRoute
  '/endless': typeof AppEndlessRoute
  '/levels/$levelId': typeof AppLevelsLevelIdRoute
  '/play/$poemId': typeof AppPlayPoemIdRoute
  '/practice/$poemId': typeof AppPracticePoemIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/levels/': typeof AppLevelsIndexRoute
  '/library/': typeof AppLibraryIndexRoute
  '/practice/': typeof AppPracticeIndexRoute
  '/library/$collectionId/': typeof AppLibraryCollectionIdIndexRoute
  '/library/$collectionId/$chapterId/$authorId': typeof AppLibraryCollectionIdChapterIdAuthorIdRoute
  '/library/$collectionId/$chapterId/': typeof AppLibraryCollectionIdChapterIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/achievements': typeof AppAchievementsRoute
  '/endless': typeof AppEndlessRoute
  '/': typeof AppIndexRoute
  '/levels/$levelId': typeof AppLevelsLevelIdRoute
  '/play/$poemId': typeof AppPlayPoemIdRoute
  '/practice/$poemId': typeof AppPracticePoemIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/levels': typeof AppLevelsIndexRoute
  '/library': typeof AppLibraryIndexRoute
  '/practice': typeof AppPracticeIndexRoute
  '/library/$collectionId': typeof AppLibraryCollectionIdIndexRoute
  '/library/$collectionId/$chapterId/$authorId': typeof AppLibraryCollectionIdChapterIdAuthorIdRoute
  '/library/$collectionId/$chapterId': typeof AppLibraryCollectionIdChapterIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/achievements': typeof AppAchievementsRoute
  '/_app/endless': typeof AppEndlessRoute
  '/_app/': typeof AppIndexRoute
  '/_app/levels/$levelId': typeof AppLevelsLevelIdRoute
  '/_app/play/$poemId': typeof AppPlayPoemIdRoute
  '/_app/practice/$poemId': typeof AppPracticePoemIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/levels/': typeof AppLevelsIndexRoute
  '/_app/library/': typeof AppLibraryIndexRoute
  '/_app/practice/': typeof AppPracticeIndexRoute
  '/_app/library/$collectionId/': typeof AppLibraryCollectionIdIndexRoute
  '/_app/library/$collectionId/$chapterId/$authorId': typeof AppLibraryCollectionIdChapterIdAuthorIdRoute
  '/_app/library/$collectionId/$chapterId/': typeof AppLibraryCollectionIdChapterIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/achievements'
    | '/endless'
    | '/levels/$levelId'
    | '/play/$poemId'
    | '/practice/$poemId'
    | '/api/auth/$'
    | '/levels/'
    | '/library/'
    | '/practice/'
    | '/library/$collectionId/'
    | '/library/$collectionId/$chapterId/$authorId'
    | '/library/$collectionId/$chapterId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/achievements'
    | '/endless'
    | '/'
    | '/levels/$levelId'
    | '/play/$poemId'
    | '/practice/$poemId'
    | '/api/auth/$'
    | '/levels'
    | '/library'
    | '/practice'
    | '/library/$collectionId'
    | '/library/$collectionId/$chapterId/$authorId'
    | '/library/$collectionId/$chapterId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/achievements'
    | '/_app/endless'
    | '/_app/'
    | '/_app/levels/$levelId'
    | '/_app/play/$poemId'
    | '/_app/practice/$poemId'
    | '/api/auth/$'
    | '/_app/levels/'
    | '/_app/library/'
    | '/_app/practice/'
    | '/_app/library/$collectionId/'
    | '/_app/library/$collectionId/$chapterId/$authorId'
    | '/_app/library/$collectionId/$chapterId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/achievements': {
      id: '/_app/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AppAchievementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/endless': {
      id: '/_app/endless'
      path: '/endless'
      fullPath: '/endless'
      preLoaderRoute: typeof AppEndlessRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/levels/': {
      id: '/_app/levels/'
      path: '/levels'
      fullPath: '/levels/'
      preLoaderRoute: typeof AppLevelsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/levels/$levelId': {
      id: '/_app/levels/$levelId'
      path: '/levels/$levelId'
      fullPath: '/levels/$levelId'
      preLoaderRoute: typeof AppLevelsLevelIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library/': {
      id: '/_app/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof AppLibraryIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/play/$poemId': {
      id: '/_app/play/$poemId'
      path: '/play/$poemId'
      fullPath: '/play/$poemId'
      preLoaderRoute: typeof AppPlayPoemIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/practice/': {
      id: '/_app/practice/'
      path: '/practice'
      fullPath: '/practice/'
      preLoaderRoute: typeof AppPracticeIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/practice/$poemId': {
      id: '/_app/practice/$poemId'
      path: '/practice/$poemId'
      fullPath: '/practice/$poemId'
      preLoaderRoute: typeof AppPracticePoemIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/library/$collectionId/': {
      id: '/_app/library/$collectionId/'
      path: '/library/$collectionId'
      fullPath: '/library/$collectionId/'
      preLoaderRoute: typeof AppLibraryCollectionIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library/$collectionId/$chapterId/': {
      id: '/_app/library/$collectionId/$chapterId/'
      path: '/library/$collectionId/$chapterId'
      fullPath: '/library/$collectionId/$chapterId/'
      preLoaderRoute: typeof AppLibraryCollectionIdChapterIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library/$collectionId/$chapterId/$authorId': {
      id: '/_app/library/$collectionId/$chapterId/$authorId'
      path: '/library/$collectionId/$chapterId/$authorId'
      fullPath: '/library/$collectionId/$chapterId/$authorId'
      preLoaderRoute: typeof AppLibraryCollectionIdChapterIdAuthorIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAchievementsRoute: typeof AppAchievementsRoute
  AppEndlessRoute: typeof AppEndlessRoute
  AppIndexRoute: typeof AppIndexRoute
  AppLevelsLevelIdRoute: typeof AppLevelsLevelIdRoute
  AppPlayPoemIdRoute: typeof AppPlayPoemIdRoute
  AppPracticePoemIdRoute: typeof AppPracticePoemIdRoute
  AppLevelsIndexRoute: typeof AppLevelsIndexRoute
  AppLibraryIndexRoute: typeof AppLibraryIndexRoute
  AppPracticeIndexRoute: typeof AppPracticeIndexRoute
  AppLibraryCollectionIdIndexRoute: typeof AppLibraryCollectionIdIndexRoute
  AppLibraryCollectionIdChapterIdAuthorIdRoute: typeof AppLibraryCollectionIdChapterIdAuthorIdRoute
  AppLibraryCollectionIdChapterIdIndexRoute: typeof AppLibraryCollectionIdChapterIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAchievementsRoute: AppAchievementsRoute,
  AppEndlessRoute: AppEndlessRoute,
  AppIndexRoute: AppIndexRoute,
  AppLevelsLevelIdRoute: AppLevelsLevelIdRoute,
  AppPlayPoemIdRoute: AppPlayPoemIdRoute,
  AppPracticePoemIdRoute: AppPracticePoemIdRoute,
  AppLevelsIndexRoute: AppLevelsIndexRoute,
  AppLibraryIndexRoute: AppLibraryIndexRoute,
  AppPracticeIndexRoute: AppPracticeIndexRoute,
  AppLibraryCollectionIdIndexRoute: AppLibraryCollectionIdIndexRoute,
  AppLibraryCollectionIdChapterIdAuthorIdRoute:
    AppLibraryCollectionIdChapterIdAuthorIdRoute,
  AppLibraryCollectionIdChapterIdIndexRoute:
    AppLibraryCollectionIdChapterIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
