/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAchievementsRouteImport } from './routes/_app/achievements'
import { Route as AppEndlessRouteImport } from './routes/_app/endless'
import { Route as AppPracticeRouteImport } from './routes/_app/practice'
import { Route as AppStoryRouteImport } from './routes/_app/story'
import { Route as AppPlayLevelIdRouteImport } from './routes/_app/play.$levelId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAchievementsRoute = AppAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => AppRoute,
} as any)
const AppEndlessRoute = AppEndlessRouteImport.update({
  id: '/endless',
  path: '/endless',
  getParentRoute: () => AppRoute,
} as any)
const AppPracticeRoute = AppPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => AppRoute,
} as any)
const AppStoryRoute = AppStoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => AppRoute,
} as any)
const AppPlayLevelIdRoute = AppPlayLevelIdRouteImport.update({
  id: '/play/$levelId',
  path: '/play/$levelId',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/achievements': typeof AppAchievementsRoute
  '/endless': typeof AppEndlessRoute
  '/practice': typeof AppPracticeRoute
  '/story': typeof AppStoryRoute
  '/play/$levelId': typeof AppPlayLevelIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/achievements': typeof AppAchievementsRoute
  '/endless': typeof AppEndlessRoute
  '/practice': typeof AppPracticeRoute
  '/story': typeof AppStoryRoute
  '/': typeof AppIndexRoute
  '/play/$levelId': typeof AppPlayLevelIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/achievements': typeof AppAchievementsRoute
  '/_app/endless': typeof AppEndlessRoute
  '/_app/practice': typeof AppPracticeRoute
  '/_app/story': typeof AppStoryRoute
  '/_app/': typeof AppIndexRoute
  '/_app/play/$levelId': typeof AppPlayLevelIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/achievements'
    | '/endless'
    | '/practice'
    | '/story'
    | '/play/$levelId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/achievements'
    | '/endless'
    | '/practice'
    | '/story'
    | '/'
    | '/play/$levelId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/achievements'
    | '/_app/endless'
    | '/_app/practice'
    | '/_app/story'
    | '/_app/'
    | '/_app/play/$levelId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/achievements': {
      id: '/_app/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AppAchievementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/endless': {
      id: '/_app/endless'
      path: '/endless'
      fullPath: '/endless'
      preLoaderRoute: typeof AppEndlessRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/practice': {
      id: '/_app/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof AppPracticeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/story': {
      id: '/_app/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof AppStoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/play/$levelId': {
      id: '/_app/play/$levelId'
      path: '/play/$levelId'
      fullPath: '/play/$levelId'
      preLoaderRoute: typeof AppPlayLevelIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAchievementsRoute: typeof AppAchievementsRoute
  AppEndlessRoute: typeof AppEndlessRoute
  AppPracticeRoute: typeof AppPracticeRoute
  AppStoryRoute: typeof AppStoryRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPlayLevelIdRoute: typeof AppPlayLevelIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAchievementsRoute: AppAchievementsRoute,
  AppEndlessRoute: AppEndlessRoute,
  AppPracticeRoute: AppPracticeRoute,
  AppStoryRoute: AppStoryRoute,
  AppIndexRoute: AppIndexRoute,
  AppPlayLevelIdRoute: AppPlayLevelIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
