/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAchievementsRouteImport } from './routes/_app/achievements'
import { Route as AppEndlessRouteImport } from './routes/_app/endless'
import { Route as AppPracticeRouteImport } from './routes/_app/practice'
import { Route as AppPlayPoemIdRouteImport } from './routes/_app/play.$poemId'
import { Route as AppTourIndexRouteImport } from './routes/_app/tour/index'
import { Route as AppTourCollectionIdRouteImport } from './routes/_app/tour/$collectionId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppTourCollectionIdIndexRouteImport } from './routes/_app/tour/$collectionId/index'
import { Route as AppTourCollectionIdChapterIdRouteImport } from './routes/_app/tour/$collectionId/$chapterId'
import { Route as AppTourCollectionIdChapterIdIndexRouteImport } from './routes/_app/tour/$collectionId/$chapterId/index'
import { Route as AppTourCollectionIdChapterIdAuthorIdRouteImport } from './routes/_app/tour/$collectionId/$chapterId/$authorId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAchievementsRoute = AppAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => AppRoute,
} as any)
const AppEndlessRoute = AppEndlessRouteImport.update({
  id: '/endless',
  path: '/endless',
  getParentRoute: () => AppRoute,
} as any)
const AppPracticeRoute = AppPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => AppRoute,
} as any)
const AppPlayPoemIdRoute = AppPlayPoemIdRouteImport.update({
  id: '/play/$poemId',
  path: '/play/$poemId',
  getParentRoute: () => AppRoute,
} as any)
const AppTourIndexRoute = AppTourIndexRouteImport.update({
  id: '/tour/',
  path: '/tour/',
  getParentRoute: () => AppRoute,
} as any)
const AppTourCollectionIdRoute = AppTourCollectionIdRouteImport.update({
  id: '/tour/$collectionId',
  path: '/tour/$collectionId',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTourCollectionIdIndexRoute =
  AppTourCollectionIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppTourCollectionIdRoute,
  } as any)
const AppTourCollectionIdChapterIdRoute =
  AppTourCollectionIdChapterIdRouteImport.update({
    id: '/$chapterId',
    path: '/$chapterId',
    getParentRoute: () => AppTourCollectionIdRoute,
  } as any)
const AppTourCollectionIdChapterIdIndexRoute =
  AppTourCollectionIdChapterIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppTourCollectionIdChapterIdRoute,
  } as any)
const AppTourCollectionIdChapterIdAuthorIdRoute =
  AppTourCollectionIdChapterIdAuthorIdRouteImport.update({
    id: '/$authorId',
    path: '/$authorId',
    getParentRoute: () => AppTourCollectionIdChapterIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/achievements': typeof AppAchievementsRoute
  '/endless': typeof AppEndlessRoute
  '/practice': typeof AppPracticeRoute
  '/play/$poemId': typeof AppPlayPoemIdRoute
  '/tour/$collectionId': typeof AppTourCollectionIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/tour/': typeof AppTourIndexRoute
  '/tour/$collectionId/$chapterId': typeof AppTourCollectionIdChapterIdRouteWithChildren
  '/tour/$collectionId/': typeof AppTourCollectionIdIndexRoute
  '/tour/$collectionId/$chapterId/$authorId': typeof AppTourCollectionIdChapterIdAuthorIdRoute
  '/tour/$collectionId/$chapterId/': typeof AppTourCollectionIdChapterIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/achievements': typeof AppAchievementsRoute
  '/endless': typeof AppEndlessRoute
  '/practice': typeof AppPracticeRoute
  '/': typeof AppIndexRoute
  '/play/$poemId': typeof AppPlayPoemIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/tour': typeof AppTourIndexRoute
  '/tour/$collectionId': typeof AppTourCollectionIdIndexRoute
  '/tour/$collectionId/$chapterId/$authorId': typeof AppTourCollectionIdChapterIdAuthorIdRoute
  '/tour/$collectionId/$chapterId': typeof AppTourCollectionIdChapterIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/achievements': typeof AppAchievementsRoute
  '/_app/endless': typeof AppEndlessRoute
  '/_app/practice': typeof AppPracticeRoute
  '/_app/': typeof AppIndexRoute
  '/_app/play/$poemId': typeof AppPlayPoemIdRoute
  '/_app/tour/$collectionId': typeof AppTourCollectionIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/tour/': typeof AppTourIndexRoute
  '/_app/tour/$collectionId/$chapterId': typeof AppTourCollectionIdChapterIdRouteWithChildren
  '/_app/tour/$collectionId/': typeof AppTourCollectionIdIndexRoute
  '/_app/tour/$collectionId/$chapterId/$authorId': typeof AppTourCollectionIdChapterIdAuthorIdRoute
  '/_app/tour/$collectionId/$chapterId/': typeof AppTourCollectionIdChapterIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/achievements'
    | '/endless'
    | '/practice'
    | '/play/$poemId'
    | '/tour/$collectionId'
    | '/api/auth/$'
    | '/tour/'
    | '/tour/$collectionId/$chapterId'
    | '/tour/$collectionId/'
    | '/tour/$collectionId/$chapterId/$authorId'
    | '/tour/$collectionId/$chapterId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/achievements'
    | '/endless'
    | '/practice'
    | '/'
    | '/play/$poemId'
    | '/api/auth/$'
    | '/tour'
    | '/tour/$collectionId'
    | '/tour/$collectionId/$chapterId/$authorId'
    | '/tour/$collectionId/$chapterId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/achievements'
    | '/_app/endless'
    | '/_app/practice'
    | '/_app/'
    | '/_app/play/$poemId'
    | '/_app/tour/$collectionId'
    | '/api/auth/$'
    | '/_app/tour/'
    | '/_app/tour/$collectionId/$chapterId'
    | '/_app/tour/$collectionId/'
    | '/_app/tour/$collectionId/$chapterId/$authorId'
    | '/_app/tour/$collectionId/$chapterId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/achievements': {
      id: '/_app/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AppAchievementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/endless': {
      id: '/_app/endless'
      path: '/endless'
      fullPath: '/endless'
      preLoaderRoute: typeof AppEndlessRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/practice': {
      id: '/_app/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof AppPracticeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/play/$poemId': {
      id: '/_app/play/$poemId'
      path: '/play/$poemId'
      fullPath: '/play/$poemId'
      preLoaderRoute: typeof AppPlayPoemIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tour/': {
      id: '/_app/tour/'
      path: '/tour'
      fullPath: '/tour/'
      preLoaderRoute: typeof AppTourIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tour/$collectionId': {
      id: '/_app/tour/$collectionId'
      path: '/tour/$collectionId'
      fullPath: '/tour/$collectionId'
      preLoaderRoute: typeof AppTourCollectionIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tour/$collectionId/': {
      id: '/_app/tour/$collectionId/'
      path: '/'
      fullPath: '/tour/$collectionId/'
      preLoaderRoute: typeof AppTourCollectionIdIndexRouteImport
      parentRoute: typeof AppTourCollectionIdRoute
    }
    '/_app/tour/$collectionId/$chapterId': {
      id: '/_app/tour/$collectionId/$chapterId'
      path: '/$chapterId'
      fullPath: '/tour/$collectionId/$chapterId'
      preLoaderRoute: typeof AppTourCollectionIdChapterIdRouteImport
      parentRoute: typeof AppTourCollectionIdRoute
    }
    '/_app/tour/$collectionId/$chapterId/': {
      id: '/_app/tour/$collectionId/$chapterId/'
      path: '/'
      fullPath: '/tour/$collectionId/$chapterId/'
      preLoaderRoute: typeof AppTourCollectionIdChapterIdIndexRouteImport
      parentRoute: typeof AppTourCollectionIdChapterIdRoute
    }
    '/_app/tour/$collectionId/$chapterId/$authorId': {
      id: '/_app/tour/$collectionId/$chapterId/$authorId'
      path: '/$authorId'
      fullPath: '/tour/$collectionId/$chapterId/$authorId'
      preLoaderRoute: typeof AppTourCollectionIdChapterIdAuthorIdRouteImport
      parentRoute: typeof AppTourCollectionIdChapterIdRoute
    }
  }
}

interface AppTourCollectionIdChapterIdRouteChildren {
  AppTourCollectionIdChapterIdAuthorIdRoute: typeof AppTourCollectionIdChapterIdAuthorIdRoute
  AppTourCollectionIdChapterIdIndexRoute: typeof AppTourCollectionIdChapterIdIndexRoute
}

const AppTourCollectionIdChapterIdRouteChildren: AppTourCollectionIdChapterIdRouteChildren =
  {
    AppTourCollectionIdChapterIdAuthorIdRoute:
      AppTourCollectionIdChapterIdAuthorIdRoute,
    AppTourCollectionIdChapterIdIndexRoute:
      AppTourCollectionIdChapterIdIndexRoute,
  }

const AppTourCollectionIdChapterIdRouteWithChildren =
  AppTourCollectionIdChapterIdRoute._addFileChildren(
    AppTourCollectionIdChapterIdRouteChildren,
  )

interface AppTourCollectionIdRouteChildren {
  AppTourCollectionIdChapterIdRoute: typeof AppTourCollectionIdChapterIdRouteWithChildren
  AppTourCollectionIdIndexRoute: typeof AppTourCollectionIdIndexRoute
}

const AppTourCollectionIdRouteChildren: AppTourCollectionIdRouteChildren = {
  AppTourCollectionIdChapterIdRoute:
    AppTourCollectionIdChapterIdRouteWithChildren,
  AppTourCollectionIdIndexRoute: AppTourCollectionIdIndexRoute,
}

const AppTourCollectionIdRouteWithChildren =
  AppTourCollectionIdRoute._addFileChildren(AppTourCollectionIdRouteChildren)

interface AppRouteChildren {
  AppAchievementsRoute: typeof AppAchievementsRoute
  AppEndlessRoute: typeof AppEndlessRoute
  AppPracticeRoute: typeof AppPracticeRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPlayPoemIdRoute: typeof AppPlayPoemIdRoute
  AppTourCollectionIdRoute: typeof AppTourCollectionIdRouteWithChildren
  AppTourIndexRoute: typeof AppTourIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAchievementsRoute: AppAchievementsRoute,
  AppEndlessRoute: AppEndlessRoute,
  AppPracticeRoute: AppPracticeRoute,
  AppIndexRoute: AppIndexRoute,
  AppPlayPoemIdRoute: AppPlayPoemIdRoute,
  AppTourCollectionIdRoute: AppTourCollectionIdRouteWithChildren,
  AppTourIndexRoute: AppTourIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
